### ISSUE TITLE
KC5.1.1: CommonsShare setup; integrated with PIVOT 

### ISSUE THREAD

**Issue by KCB13** [heliumdatacommons/MVP-repo#8]
Owner: Ray 
Doer(s): @rayi113 @hyi

**Comment by KCB13** [comment]
Refer to https://github.com/heliumdatacommons/commonsshare

**Comment by hyi** [comment]
@KCB13 Although the code repo for CommonsShare is setup here: https://github.com/heliumdatacommons/commonsshare, @rayi113 and I have been working on setting up the test and production servers for CommonsShare before deploying the code to servers following standard software release process. If this issue covers server setup, it may not be closed yet since we have not finished setting up the server stack yet.
